services:
  db:
    image: mysql:8.0
    container_name: piyachok_local_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piyachok
    ports:
      - "3307:3306"
    volumes:
      - piyachok_mysql_data:/var/lib/mysql

volumes:
  piyachok_mysql_data: